name: Setup Depot
description: Installs the Depot CLI into the GitHub Actions environment
author: Depot
branding:
  icon: package
  color: gray-dark
runs:
  using: node20
  main: dist/index.js
inputs:
  version:
    description: |-
      Version of the Depot CLI to install. If unspecified or set to "latest",
      the latest version for the target platform will be installed. Example: "0.0.2".
    default: latest
    required: false
  oidc:
    description: |-
      If set to true, the action will authenticate with the Depot API using OIDC
      and save the returned token as environment a `DEPOT_TOKEN` environment variable.
    default: 'false'
    required: false
